#!/usr/bin/env bash

# Enforce univ-cotedazur email

regex='.*?@etu\.univ-cotedazur\.fr'
email="$(git config user.email)"


if ! $(echo "$email" | grep -Eq  "$regex")
then
	echo "Invalid email. Please run the following command before committing: 'git config user.email your-name@etu.univ-cotedazur.fr"
	exit 1
else
	exit 0
fi


